# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_locatorprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatorprofile',
            name='birth_certificate_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_birth_certificate',
            field=models.FileField(upload_to='birth_certificate'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_clearance',
            field=models.FileField(upload_to='clearance'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_national_card',
            field=models.FileField(upload_to='national_cards/'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='national_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
