# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0006_remove_locatorprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_national_card',
            field=models.FileField(upload_to='national_cards'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
