# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0010_auto_20170702_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatorprofile',
            name='Second_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificate'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_clearance',
            field=models.FileField(blank=True, null=True, upload_to='clearance'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='image_of_national_card',
            field=models.FileField(blank=True, null=True, upload_to='national_cards'),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locatorprofile',
            name='relative_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
