# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('isf', 'Isfahan'), ('teh', 'Tehran'), ('shr', 'shiraz')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('year_of_construction', models.BigIntegerField()),
                ('total_area', models.BigIntegerField()),
                ('construction_area', models.BigIntegerField()),
                ('num_of_bed_rooms', models.BigIntegerField()),
                ('max_num_of_people', models.BigIntegerField()),
                ('allowed_more_people', models.BooleanField()),
                ('allowed_pet', models.BooleanField()),
                ('place_type', models.CharField(choices=[('v', 'villa'), ('g', 'garden'), ('h', 'house'), ('s', 'suite')], max_length=1)),
                ('start_rental_period', models.DateField(blank=True, null=True)),
                ('end_rental_period', models.DateField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('assignment_time', models.TimeField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('price_for_each_more_person', models.BigIntegerField(blank=True, null=True)),
                ('rental_conditions', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('services', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('surroundings', models.TextField(blank=True, null=True)),
                ('distance_from_store', models.BigIntegerField(blank=True, null=True)),
                ('distance_from_restaurant', models.BigIntegerField(blank=True, null=True)),
                ('home_document_file', models.FileField(upload_to='home_document_file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
