# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='price',
            new_name='price_per_night',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('v', 'villa'), ('g', 'garden'), ('h', 'house'), ('s', 'suite'), ('o', 'other')], max_length=1),
        ),
    ]
