# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_app', '0002_auto_20170711_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('t', 'temporarily_reserved'), ('p', 'payed')], max_length=1)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='max_num_of_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='year_of_construction',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='renting',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_app.Place'),
        ),
        migrations.AddField(
            model_name='renting',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
