# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_app', '0004_auto_20170712_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='status',
            field=models.CharField(choices=[('t', 'temporarily_reserved'), ('r', 'reserved')], default='t', max_length=1),
        ),
    ]
