# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_app', '0008_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.FileField(upload_to='image_file'),
        ),
    ]
