# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_app', '0009_auto_20170716_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
