# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_renterprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='renterprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='birth_certificate_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='image_of_birth_certificate',
            field=models.FileField(upload_to='birth_certificate'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='image_of_national_card',
            field=models.FileField(upload_to='national_cards/'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='national_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
