# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0003_auto_20170627_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renterprofile',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='image_of_birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='birth_certificate'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='image_of_national_card',
            field=models.FileField(blank=True, null=True, upload_to='national_cards'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
