# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0011_auto_20170706_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locatorprofile',
            old_name='Second_contact_number',
            new_name='second_contact_number',
        ),
    ]
