# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='confirmation_key',
            field=models.CharField(max_length=50),
        ),
    ]
